### ISSUE TITLE
jt decoded incorrectly encode the date 

### ISSUE THREAD

**Issue by LarsenDR** [ka9q/ka9q-radio#43]
New jt-decoded encoded date in the ALL_WSPR.TXT file as 1018_1 when it should be 1018 for today

1018_1 1000 -17  0.37  14.0970026  WA6HEW EM11 23          0  0.55  1  1    0  0  21     1   471
1018_1 1000 -20  0.24  14.0970151  AJ4EO/2 23              0  0.33  2  1    0  0  34  4685  -109
1018_1 1000 -14  0.32  14.0970167  W3ENR FM28 23           0  0.27  1  1    0  0  19     1   227
1018_1 1000 -21  0.28  14.0970258  W4DES EL97 37           0  0.21  1  1    0  0  30     7   101
1018_1 1000   2  0.19  14.0970414  N8NJ EN81 30            0  0.84  1  1    0  0  19     1   385

it should be 
1018 1000 -17  0.37  14.0970026  WA6HEW EM11 23          0  0.55  1  1    0  0  21     1   471
1018 1000 -20  0.24  14.0970151  AJ4EO/2 23              0  0.33  2  1    0  0  34  4685  -109
1018 1000 -14  0.32  14.0970167  W3ENR FM28 23           0  0.27  1  1    0  0  19     1   227
1018 1000 -21  0.28  14.0970258  W4DES EL97 37           0  0.21  1  1    0  0  30     7   101
1018 1000   2  0.19  14.0970414  N8NJ EN81 30            0  0.84  1  1    0  0  19     1   385

**Comment by ka9q** [comment]
I don't see any underscores in my own wspr logs, including from that period. The problem was that the standard versions of wsjtx and ft8_lib weren't designed to run in the multichannel ka9q-radio environment, so I made my own forks with modifications to the input file name and output logging formats. Perhaps you were using a version of wsprd that didn't match what I was expecting. Since the originals of those programs are pretty stable now, I'd like to come up with some backward compatible modifications so I could eliminate the need for my forked versions.
